services:
    db:
        image: mysql:latest
        restart: unless-stopped
        env_file:
            - .env
        environment:
            - MYSQL_ROOT_HOST=%
            - MYSQL_ROOT_PASSWORD=${db_password}
        ports:
            - 3306:3306
